name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Debezium master branch
      uses: actions/checkout@v2
      with:
        repository: 'igabaydulin/debezium'
        ref: 'master'
        persist-credentials: 'false'
        clean: 'true'
        fetch-depth: '1'
        lfs: 'false'
    - name: Build Debezium
      run: MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR" mvn clean install -Passembly -DskipITs -DskipTests -pl debezium-connector-postgres -pl debezium-embedded -pl support/ide-configs
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Checkout Back to Project
      uses: actions/checkout@v2
    - run: ./gradlew test
