name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Debezium master branch
      uses: actions/checkout@v2
      with:
        repository: 'igabaydulin/debezium'
        ref: 'master'
        persist-credentials: 'false'
        #path: ''
        clean: 'true'
        fetch-depth: '1'
        lfs: 'false'
    - name: Check folder
      run: ls
    - name: Build Debezium
      run: |
        cd debezium
        mvn clean install -Passembly -DskipITs -DskipTests
    - name: Run Tests
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: ./gradlew test
