name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'igabaydulin/debezium'
        ref: 'master'
        persist-credentials: 'false'
        #path: ''
        clean: 'true'
        fetch-depth: '1'
        lfs: 'false'
